@Library('shared-library@main') _
pipeline {
    agent any

    stages {

        stage('deploy') {
            steps {
                script{
                    def config=[namespace:"app4",yaml:"k8s/app4.yaml"]
                    deployApp(config)
              }
            }
        }
    }

    post {
        success {
            echo 'app4 deploy completato con successo'
        }
        failure {
            echo 'Errore nel deploy app4'
        }
    }
}
